mod ask;
mod colors;
mod dino;
mod duel;
mod eightball;
mod mixu;
mod quote;
mod rockpaperscissors;
mod rpg;
mod sudoku;

pub use ask::*;
pub use colors::*;
pub use dino::*;
pub use duel::*;
pub use eightball::eightball;
pub use mixu::*;
pub use quote::*;
pub use rockpaperscissors::*;
pub use rpg::*;
pub use sudoku::*;
